### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by likping** [SIA-IDE/BearLLM#4]
This is pioneering work in applying large language models to fault diagnosis.
After downloading the data from Hugging Face and creating a simple `.env `file, the tests worked. However, I noticed that the database data differs from what is required in the `src/demo.py ` of the bearllm project. 
**A simple example would help illustrate how large language models can assist in fault diagnosis.** I look forward to further advancements in the research of fault diagnosis and large language models.

**Comment by hatton613** [comment]
The current demo primarily offers a pseudocode example for the inference process, aiding in understanding the methods described in the paper. It requires some modifications and debugging before it can be directly executed. To get started, we need to **construct a cache dataset** using `condition_id` and `label` (pairing test signals with fault-free reference signals), and **fine-tune the LLM using a corpus dataset**. We're currently reviewing the corpus for any violations or sensitive content, with the goal of releasing the corpus portion of the MBHM dataset publicly and refining the demo code.

**Comment by likping** [comment]
Great, I will try to adapt the example code based on my understanding of the paper's approach, so that it can be run directly. Thank you for your reply.
